name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup qemu
      uses: docker/setup-qemu-action@v3
    - uses: actions/checkout@v4
    - name: Build kernel
      run: cargo build --verbose
      working-directory: kernel/
    - name: Run kernel tests
      run: cargo test --verbose
      working-directory: kernel/
